In [8]:
import numpy as np
palabras={"alargue":0, "automovil":1, "casa":2, "novedoso":3, "SPAM":4}

dataset= np.array([[3,3,1,6,1],[1,4,7,1,0],[1,4,3,1,0],[4,2,1,5,1],[1,3,4,2,0],[2,4,5,1,0]])
print(dataset)

cant_palabras_x_mail = [sum(e) for e in dataset]
print(cant_palabras_x_mail)

probabilidades = []
for i in range(1,6):
    mail = dataset[i]
    for j in range(0,3):
        probablidades.append(mail[j] / cant_palabras_x_mail[i])
    
print(probablidades)

[[3 3 1 6 1]
 [1 4 7 1 0]
 [1 4 3 1 0]
 [4 2 1 5 1]
 [1 3 4 2 0]
 [2 4 5 1 0]]
[14, 13, 9, 13, 10, 12]


AttributeError: 'numpy.float64' object has no attribute 'append'